name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  # state manager
  flutter_bloc: ^8.1.6

  # router
  go_router: ^14.2.7

  # dependency injection
  get_it: ^7.7.0

  # equatable
  equatable: ^2.0.5

  # svg pictures
  flutter_svg: ^2.0.10+1

  # rest api
  dio: ^5.7.0

  # assets generator
  flutter_gen: ^5.7.0

  # package that stores bloc state
  hydrated_bloc: ^9.1.5

  # path provider
  path_provider: ^2.1.4

  # geo locator
  geolocator: ^13.0.1

  # shimmer effect
  skeletonizer: ^1.4.2

  # intl
  intl: ^0.19.0

  # json annotation
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # lints
  flutter_lints: ^4.0.0
  # dio logger
  talker_dio_logger: ^4.4.1
  # assets generator
  flutter_gen_runner: ^5.7.0
  # build runner
  build_runner: ^2.4.12
  json_serializable: ^6.8.0


flutter_gen:
  output: lib/core/utils/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
